### ISSUE TITLE
PSR6/PSR16 cache support

### ISSUE THREAD

**Issue by mrcnpdlk** [tboothman/imdbphp#112]
Is any option to support PSR6/16 cache interface against `Imdb\CacheInterface`?

**Comment by tboothman** [comment]
Sorry for the really slow response.
At the time of adding the caching interface to this library I don't think PSR16 existed -- PSR-6 is overly complex which is why no PSR interfaces are supported as it stands.
I'm sure you noticed that `Imdb\CacheInterface` is basically a subset of the PSR16 interface and you've probably worked around it by implementing `Imdb\CacheInterface` on a PSR-16 cache.

I'll look to implementing PSR16 or at a minimum making `Imdb\CacheInterface` a subset of PSR-16 so it's easy to plug a PSR-16 cache in.
I'll probably take a look this weekend and release it with the breaking changes for removing the budget methods that no longer work

**Comment by tboothman** [comment]
This should do it. I've not actually tried it with a different cache but it only calls get and set, and I've changed set to call with a TTL (which isn't used in the default file cache) https://github.com/tboothman/imdbphp/commit/3fed7e8123e79df421b2c2b17f8f2cfc6432de42#diff-a511abcc5274722baaa01030ee4dc591R103
I almost accidentally left it purging the whole cache on startup but it won't do that any more :D

**Comment by tboothman** [comment]
Released [v6.0](https://github.com/tboothman/imdbphp/releases/tag/v6.0.0) which should resolve this. Let me know if it doesn't do what it should
