### ISSUE TITLE
BoxOffice Chart not working right

### ISSUE THREAD

**Issue by parham-box** [tboothman/imdbphp#115]
when box office chart is printed id for the first movie is wrong but every thing else works fine

**Comment by jreklund** [comment]
Everything under /boxoffice/ have been removed and put under IMDb Pro, so that information aren't available to us anymore. More information here:
https://github.com/tboothman/imdbphp/releases/tag/v5.2.5

What function are you referring to exactly?

**Comment by tboothman** [comment]
@parham-box which methods are you wanting to work?

As I wrote in the release message the only data available now is 
```
Opening Weekend: $8,898,000 (Japan), 29 July 2002, Limited Release
Opening Weekend USA: $449,839, 22 September 2002, Limited Release
Gross USA: $10,055,859
Cumulative Worldwide Gross: $274,925,095
```
so unless you're after any of that you're out of luck. I'm going to be removing all the business methods at the weekend unless someone requests otherwise. I'm not sure it's even possible to resurrect to work like they used to.
