### ISSUE TITLE
fr-FR don't work

### ISSUE THREAD

**Issue by Machou** [tboothman/imdbphp#117]
Hello

I Search Movie or Serie with config fr-FR / en-US like :

```
try {
	$config = new \Imdb\Config();
	$config->language = 'fr-FR, fr, en-US, en';

	$search = new \Imdb\TitleSearch($config);
}

catch (Exception $e) {
	$results = null;
	echo 'error with search';
}
```

**_Results Examples_**

> French Name : **Jigsaw**
> English Name : **Jigsaw**
> IMDb ID : [tt3348730](https://www.imdb.com/title/tt3348730/)
> Name with _fr-FR_ : Fűrész: Újra játékban
> Name with _en-US_ : Jigsaw
> 
> It's with Hungary, i don't know why.

> French Name : **Very Bad Dads 2**
> English Name : **Daddy's Home 2**
> IMDb ID : [tt5657846](https://www.imdb.com/title/tt5657846/)
> Name with _fr-FR_ : Megjött apuci! 2.
> Name with _en-US_ : Megjött apuci! 2.
> 
> It's with Hungary too, i don't know why.

Can you fix ?

Thanks !

**Comment by jreklund** [comment]
My first analys are that IMDb hate french at the moment. You can't even get it to work by changing your "Site preferences" on your IMDb account. I have tried "France", "French Guiana", "French Polynesia" and "French Southern Territories". They fall back into "Daddy's Home 2".

I can get it to work with:  Bulgarian, Russian, Turkish, German and Polish.

Your server are located in Hungary? Then try to change your geolocation to English or France by specifying a ip-address. So that you at least get the English title.
#### Change geolocation
Sometimes your server aren't located in your preferred area (language), so you can use another ip address (e.g. a public proxy), for tricking IMDb geolocation system.
There are some movies/TV Series that have the English translation in "World-wide" and the only way to retrieve them is an US/UK IP-address.
```
$config->ip_address = '';
```

**Comment by Machou** [comment]
yes my server is in Hungary. i understand now.

Thank you for that clarification.

**Comment by Machou** [comment]
Re, sorry , i'm back. I have try with server in french with 2 hosters : _OVH_ and _Online_ (ip fr)

**_It's an example_** ( YES AN EXAMPLE, i can give many movies with this problem ) with : https://www.imdb.com/title/tt6306064/

The first Release Date i have it's **Greece** but the Release it's in **USA**.

**Comment by Machou** [comment]
Return Title::releaseInfo() for tt6306064 : https://pastebin.com/LJNDwqjh

**Comment by jreklund** [comment]
It's always going to be on that position. It's going by date and then alphabetical.
