### ISSUE TITLE
closing html tags in plot

### ISSUE THREAD

**Issue by paxter** [tboothman/imdbphp#123]
Since yesterday, there are closing html tags in plots.

For example test IMDb-ID: tt8183028

You will get for plot:
```
This is the story of a world whose territories and own frontiers were built by the slave trade. A world where violence, subjugation and profit imposed their routes.</span>
</p>
```

Not sure if it's a bug. I think a simple strip_tags() could handle that issue.

**Comment by jreklund** [comment]
Hi, thanks for the report. Should work as expected now.

**Comment by paxter** [comment]
Thanks, works as it should now. :)

**Comment by paxter** [comment]
Another problem. Try tt3513388.
Result: 
`<a href='/name/nm1024878/?ref_='>Seth Meyers</a> hosts a late-night talk show.`

**Comment by jreklund** [comment]
@tboothman I'm thinking about creating a new function separating both text (plot) and actors (people). Do you prefer camel case, _ naming schematics or lowercase, as this project utilizes these three types...
e.g.
plotOutlineDetails (plotOutlineSplit)
plotoutline_details (plotoutline_split)
plotoutlinedetails (plotoutlinesplit)

```php
[
	'plot' => 'Seth Meyers hosts a late-night talk show.',
	'people' => [
		'1024878' => 'Seth Meyers'
	]
]
```

**Comment by tboothman** [comment]
Personally I use camel case ... but it looks like whoever started this preferred snake case, so I'd go with that.

With regards to the summaries and links etc, if you look at the underlying data for this title it's `[link=nm1024878] hosts a late-night talk show.` and [the help says you can do titles](https://help.imdb.com/article/contribution/other-submission-guides/linking-names-and-titles-in-text-based-lists/G3SKJC2XJEHCMRS8) as well.

Personally if I were making this library from scratch I'd make the methods return data close to what's powering the html because then it's clear what types of values you can get from each method. There's quite a lot of dirty methods that return html that really shouldn't be in an API (like plotoutline).

In this instance the original string isn't really what anyone would want, and although I'm not sure what you would do with a list of id->name maps it's better than dropping the data. Make sure you keep titles in there though because they can be there too.

**Comment by jreklund** [comment]
I got no idea either. But I thought I would delete all HTML in plotoutline and make another function that keeps it intact. In case someone wants it intact. Personally I just want the rendered text (without html) in my script.

But what I didn't consider are that some people want the real html. Maybe a more complete array like this:
```php
[
	'text' => 'Seth Meyers hosts a late-night talk show.',
	'html' => '<a href='/name/nm1024878/?ref_='>Seth Meyers</a> hosts a late-night talk show.',
	'imdb' => '[link=nm1024878] hosts a late-night talk show.'
	'person' => [
		'nm1024878' => 'Seth Meyers'
	],
	'title' => []
]
```

Thanks for the link, I haven't even looked at imdb help section before.

**Comment by duck7000** [comment]
Multiple functions for the same output means more afford to maintain this library?

I would say use camel case and keep the data as clean as possible but make sure that all the data is included so that there is a choice of what data they want. 

Maybe include the data in multiple ways in the output array?

**Comment by duck7000** [comment]
> Personally I just want the rendered text (without html) in my script.

- This is how i use this method as well, only the text that gives a small indication of what this movie/tvseries is about.
I don't think other users will use it differently than this, so don't make it too complicated. strip_tags removes the tags but the name is still in there, so the text is still complete.
- why is there a fallback in this method? will/can the first one fail? if so, why not use the else part if that always work? is there performance gain in jsonLD?

> Maybe include the data in multiple ways in the output array?

This may still be a solid solution, include the stripped version and the raw version so everyone can choose what they want?
To include all links separately in the output array is something i would not do, i can't imagine who will use that?
if someone would want changes they always can do that in his/her application if all data is there?

Just a few thoughts

**Comment by paxter** [comment]
Looks like it's fixed by https://github.com/tboothman/imdbphp/pull/293
Thanks for keeping this awesome project alive and for all your hard work guys!
