### ISSUE TITLE
IMDB change to Title::genres?

### ISSUE THREAD

**Issue by underslung** [tboothman/imdbphp#143]
This is no longer populating in the code I'm using, did something change with the genre structure?

**Comment by jreklund** [comment]
Hi, there where a site change five days ago (#139), that have been fixed in the master. I can make an official release later today.

**Comment by underslung** [comment]
Whoops, sorry for the noise.  I didn't check closed issues.  Shall I close this or wait for the release?

**Comment by jreklund** [comment]
No worries, it's our fault for not making releases with major breakage. Keep it open. I will reference it and close it after I have finished watching Handmaid's Tale.

**Comment by duck7000** [comment]
@jreklund 
i have to agree that lately, if there where major site changes, this isn't followed by a release.
Of course i understand that you can't release a version for every small change but i do think it is better to do more releases. That way more users would use it rather than keep track of changes and use the master.

Maybe to do more releases for small fixes: 6.0.x
And for bigger or more complex fixes or changes: 6.x

**Comment by jreklund** [comment]
[v6.0.4](https://github.com/tboothman/imdbphp/releases/tag/v6.0.4) have now been released.
Generally when one functions break, something else will follow. That's why I have waited in the past with publishing a new version directly after applying a new patch.

Will keep it in mind to be more frequent with the releases.
6.x are only used when we add new functions. Every fix gets 6.0.x.
