### ISSUE TITLE
method recommendations not returning full year span (if available)

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#157]
Hi

This method is not returning full year span.
And if there is text inside the year brackets only year is fetched.

Try with this tv serie: https://www.imdb.com/title/tt1520211/

The method returns only the first year and non of the text.

Personally i use this method at the moment and it works well but uses preg_match instead of xpath

```
 public function movie_recommendations() {
	if (empty($this->movierecommendations)) {
		$this->getPage("Title");
		if ( preg_match_all('!<div class="rec-title">\s*(.*?)\s*</div>!ims', $this->page["Title"], $matches) ) {
			foreach ($matches[0] as $found){
				if (preg_match('!<a\s+href="/title/tt(\d+)/[^>]*>\s*(.+)\s*</a>!ims',$found,$match)){
					if (preg_match('!<span class="nobr">\s*(.*?)\s*</span>!ims',$found,$year)){
						$year = trim(strip_tags($year[0]));
						$this->movierecommendations[] = array('title'=>strip_tags($match[2]),'imdbid'=>$match[1],'year'=>$year);
					}
					else{
						$this->movierecommendations[] = array('title'=>strip_tags($match[2]),'imdbid'=>$match[1],'year'=>'');
					}
				}
				else{
					return $this->movierecommendations;
				}
			}
		}
	}
    return $this->movierecommendations;
  }
```

Maybe you can look in to this?

**Comment by duck7000** [comment]
I would certainly appreciate a reaction, although i understand this has no priority

**Comment by tboothman** [comment]
Honestly it's because you pasted in some code that looks nothing like the current code, and I didn't feel like unpicking whatever it is that it does (turns out it does exactly the same as the current implementation?????).
The current code works fine - it returns all recommendations for TV and film with an id, title and year. The year it returns is consistent with the year you get from the year function on a TV show (the start year). I would argue the results of recommendations should be used to fetch more metadata about the title

```
(
    [0] => Array
        (
            [title] => Stranger Things
            [imdbid] => 4574334
            [year] => 2016
        )

    [1] => Array
        (
            [title] => Game of Thrones
            [imdbid] => 0944947
            [year] => 2011
        )

    [2] => Array
        (
            [title] => Breaking Bad
            [imdbid] => 0903747
            [year] => 2008
        )

    [3] => Array
        (
            [title] => Vikings
            [imdbid] => 2306299
            [year] => 2013
        )

    [4] => Array
        (
            [title] => Black Mirror
            [imdbid] => 2085059
            [year] => 2011
        )

    [5] => Array
        (
            [title] => Friends
            [imdbid] => 0108778
            [year] => 1994
        )

    [6] => Array
        (
            [title] => The Big Bang Theory
            [imdbid] => 0898266
            [year] => 2007
        )

    [7] => Array
        (
            [title] => The Flash
            [imdbid] => 3107288
            [year] => 2014
        )

    [8] => Array
        (
            [title] => Supernatural
            [imdbid] => 0460681
            [year] => 2005
        )

    [9] => Array
        (
            [title] => Gotham
            [imdbid] => 3749900
            [year] => 2014
        )

    [10] => Array
        (
            [title] => Fear the Walking Dead
            [imdbid] => 3743822
            [year] => 2015
        )

    [11] => Array
        (
            [title] => Arrow
            [imdbid] => 2193021
            [year] => 2012
        )

)
```

**Comment by duck7000** [comment]
Wow this kind of reaction is not what i was after!

I think you miss understand my point.
It is about the recommendations of the provided link. If you look for example to friends in your above quote you notice that friends only has the FIRST year and not the year span!!

![screenshot](https://user-images.githubusercontent.com/15360048/52432185-1d22d480-2b0a-11e9-9f4c-5a3416fd2385.png)

same is true for the text inside the year brackets, although we can argue about the usefulness about that

**Comment by duck7000** [comment]
It certainly was NOT ment to upset anyone!

**Comment by duck7000** [comment]
Fine, it was only ment to make this method parse the full info that is there, but apparently this will not be appreciated here. I don't understand the hostility and:
> Honestly it's because you pasted in some code that looks nothing like the current code

So if it doesn't look like the old code it is no good or not worth the trouble reading? That is what i feel like your reaction, and you could have told me that a friendly way.

No more updates from me

**Comment by tboothman** [comment]
lol, well this has escalated a bit.
I was trying to be clear and honest, because you asked why I (or anyone else) hadn't replied to this issue. You can think that's rude if you like, but it's what I thought/did.

IIRC I had a quick look when you initially posted this to see what the problem was. You implied that the recommendation was missing/broken if there was a year span. I tested that and it wasn't the case and then I forgot to reply asking what really the problem was.

With regard to the code you posted: I still am not clear what it does. I put it in place of the current code and it does exactly the same thing.

I use this library and really would only want to spend time changing it to fix bugs to keep it working as it currently does or for fun to make it better somehow.

If someone made a pull request with some tests to prove whatever they'd added worked I'd merge it immediately - that's the perfect contribution. If someone provided a change or addition without tests I wouldn't mind spending the time to add some tests then merge it. If there's an obvious bug I'll fix it.

As for adding new stuff ... honestly .. html parsing is a bit of a pain and there's lots of edge cases and tests required (usually) to make something worth having

**Comment by tboothman** [comment]
With regards to this addition you're asking for (IMO you could have been a lot clearer in your initial post that this was a request for an additional field) I would suggest all metadata about the recommendation be fetched by creating another `\Imdb\Title`.

If you want to modify the code, please do. I don't think it'd be too much more complicated than changing the regex on https://github.com/tboothman/imdbphp/blob/master/src/Imdb/Title.php#L493 but the tests for this are pretty bad because the recommendations change so it's hard to test the cases.

**Comment by duck7000** [comment]
@tboothman 

First of all thanks for the reply
Ok well i did intrepid no reply as rude, but that is surely my interpretation so my apologies for that.

> IIRC I had a quick look when you initially posted this to see what the problem was. You implied that the recommendation was missing/broken if there was a year span. I tested that and it wasn't the case and then I forgot to reply asking what really the problem was.

> This is the output (in my program) from the above code with serie the walking dead
> Stranger Things@4574334@(TV Series 2016)
> Game of Thrones@0944947@(TV Series 2011)
> Breaking Bad@0903747@(2008–2013)
> Vikings@2306299@(TV Series 2013)
> The Big Bang Theory@0898266@(TV Series 2007)
> American Horror Story@1844624@(TV Series 2011)
> Supernatural@0460681@(TV Series 2005)
> Black Mirror@2085059@(TV Series 2011)
> Friends@0108778@(1994–2004)
> Westworld@0475784@(TV Series 2016)
> Shameless@1586680@(TV Series 2011)
> Arrow@2193021@(TV Series 2012)

This is the output of the current imdbphp code with the same serie from the above link (the walking dead)

> Stranger Things@4574334@2016
> Game of Thrones@0944947@2011
> Breaking Bad@0903747@2008
> Vikings@2306299@2013
> Black Mirror@2085059@2011
> The Big Bang Theory@0898266@2007
> The Flash@3107288@2014
> Gotham@3749900@2014
> Friends@0108778@1994
> Westworld@0475784@2016
> Fear the Walking Dead@3743822@2015
> Arrow@2193021@2012

I hope you see the difference, because that is where this is all about. That's all.
It is not about adding new stuff at all, but i'll admit that it is not a bug but a addition to year field.
I don't understand why you say that your results are the same with the original and this method? It can't be imho

i agree that parsing html is a pain though

And i apologize if i was not clear enough, and for the rant..

**Comment by duck7000** [comment]
And i don't know how a pull request works, never used it. I have read about it and it is used for multiple code change requests.
I thought that this was not the place for such request, but apparently i should have used that?

**Comment by tboothman** [comment]
Hah. I think I forgot to save the file when i pasted your code in. Far too used to using IntelliJ which autosaves when you change files .. using Netbeans at home.

Pull requests are pretty good way to get the changes you want to open source software because you've put in most of the effort - the maintainer is much more likely to accept it. If you just ask for a change: depending on how keen the maintainer is you're not likely to get much more than your request added to some backlog that might never be completed.

So the problem with your code is that the new return of the method isn't backwards compatible with the existing one. `year` used to be a number now it's a weird mix of sometimes title type and numbers, maybe two numbers in brackets. As much as possible the output of the methods in this library should return something that looks like original data. `(TV Series 2007)` isn't of great use to someone who only wants to show the year or title type. They've got to put in extra effort to split the data out - which is what the library should be doing

**Comment by duck7000** [comment]
@tboothman 

> So the problem with your code is that the new return of the method isn't backwards compatible with the existing one. `year` used to be a number now it's a weird mix of sometimes title type and numbers, maybe two numbers in brackets. As much as possible the output of the methods in this library should return something that looks like original data. `(TV Series 2007)` isn't of great use to someone who only wants to show the year or title type. They've got to put in extra effort to split the data out - which is what the library should be doing

Thanks for your reply!

Ok i have to agree that the output of year has indeed changed and that a user might not want that.
But on the other hand the year field contains not the full info that is there. That is why i said that the text and the brackets could be up for debate and certainly can be left out.
I do think that if there is a year span it should be in the year field. I can't think of a reason why a user wouldn't want that?
But agree it is a change

So to conclude it is best to leave the method like it is? for the sake of backwards compatibility that is

And next time i will use a pull request

**Comment by duck7000** [comment]
And the issue template is surely a good idea, i did know it was there...my bad!, i should have used that and next time a will

**Comment by tboothman** [comment]
I would refer you back to my original reply
> The year it returns is consistent with the year you get from the year function on a TV show (the start year). I would argue the results of recommendations should be used to fetch more metadata about the title
https://github.com/tboothman/imdbphp/blob/master/src/Imdb/Title.php#L279-L296

Easier to use what's there than add/replicate functionality. Obviously if you wanted the endyear for a title you'd have to do another fetch to get that title's page, which might not be ideal.

The only way to go here if you want the end year is to add a new field to the result (ideally called endyear). Ideally it does whatever endyear() does, I'm not sure what that is exactly.

There's at least 3 possibilities for title years. One year, one year to another year, and one year to undefined. Might be possible to have no year at all?
https://www.imdb.com/title/tt0795176/
https://www.imdb.com/title/tt0903747/
https://www.imdb.com/title/tt3638584/

**Comment by duck7000** [comment]
Thank you very much for the explaining!

I like the idea of a new field to the result array.

In that case we can simply get everything between brackets and split it up in year and (if available) endyear? It should be the same output as  endyear()?
The other text etc can be discarded.

**Comment by duck7000** [comment]
This can be closed now, new method is merged into master
