### ISSUE TITLE
 Getting photos

### ISSUE THREAD

**Issue by umair33** [tboothman/imdbphp#199]
How to get the pic for the Director writer producer etc I am able to get actors photos but how to get others

**Comment by duck7000** [comment]
That may be because in director method there is no code to get the photos.

The only way to add this is to code it in yourself and very much hope that the maintainers are willing to merge it...

Good luck with that because my experience with merging is not very good here..

I made my own fork and added (as een example) series photos but there is nobody interested here

**Comment by jreklund** [comment]
@duck7000 The last two pull request you made got closed by yourself 4 days later. We do this in our spare time, so if you would have just given us time to actually look it over. The results would likely ended up differently.

That's also why I haven't fixed everything myself in the "Issue"-queue, they aren't hard, but I lack the time. So I only go for bugs.

And regarding @umair33 question: No one have requested that feature under the active development or wanted it bad enough themselves to fix it.

**Comment by duck7000** [comment]
@jreklund 

Well i even asked if there was any interest at all.. nobody even respond so i assumed there is no interest.
Pull requests from other people are beeing merged, like from @M0H4MM4D0UTIS while that is even a addition to the method i added in the first place. Can you imagine that i got a little frustrated?

I do understand that time is an issue but by saying:
`That's also why I haven't fixed everything myself in the "Issue"-queue, they aren't hard, but I lack the time. So I only go for bugs.`
People got frustrated (including me), they don't get even a response to their issue, it would simply be better to respond to a issue and tell people why you or tboothman are not going to fix their problem. 

And regarding to this issue i agree that nobody requested it, but not everybody looks in the code to realize that the data they want not is included in the method, if they did they wouldn't asked about it i guess. I think that the poster didn't know that picture url not is included in this method because there are other methods that do include it, and simply assumed this would be true for other methods

And i believe ,and i appologies up front, to maintain this wonderfull piece of software does not only include the coding part, the issue tracker and documentation is just as importent

**Comment by tboothman** [comment]
The problem here is the discoverability of the Person class. Clearly this functionality is available but if you're at the Title class there's no obvious link between the people it returns and the Person class.

@umair33 
```php
$title = new \Imdb\Title(133093);

$directors = $title->director();

foreach ($directors as $director) {
    $person = new \Imdb\Person($director['imdb']);
    $photo = $person->photo();
    echo "{$person->name()}: $photo\n";
}
```
```
Lana Wachowski: https://m.media-amazon.com/images/M/MV5BMjEzMTc2MDQ5OV5BMl5BanBnXkFtZTcwNjkzNDY0OA@@._V1_UX214_CR0,0,214,317_AL_.jpg
Lilly Wachowski: https://m.media-amazon.com/images/M/MV5BMTU1Mjc1MjkzNV5BMl5BanBnXkFtZTgwOTc1NDQ1ODE@._V1_UX214_CR0,0,214,317_AL_.jpg
```

I'll mention the person class in the tldr at the top of the readme. The search classes are mentioned further down, one of which does return Person,

**Comment by jreklund** [comment]
**Disclaimer: This post are authored by me, and my views are my own.**

@duck7000 I didn't think I needed to answer something that you closed. I don't check on this every day, so I just saw you open and closed it.

Of course we are willing to merge good features, why wouldn't we accept an extension that's not a breaking change? Like you said. We merged your function to start with. So why would we just ignore you in the future...

Sure I'm an collaborator of this software and a couple of others. I didn't sign up for the role at all, it where just handed to me as I started to fix a couple of things I needed. At that time I had plenty of time to add new features, and now I don't. 

Sure I get it, you don't get your issue resolved. But I don't agree that everything need to be answered by us, the maintainers. As it's an open source project, everyone are welcome to contribute and answer user related questions. We aren't your personal support. And we DO accept pull request, fix bugs and update the tests. Maintain the project. But at this time, we don't add new features. And that's what's in the "Issue"-queue at the moment (except for this apparently, as it's already there).

Personally I don't remember a thread/issue popping up about us not wanting to help you guys out. I have personally helped you out on a number of occasions since 2017, so you DO know that we will help you out.

Now in the heat of "battle", it appears we already have that function (thanks @tboothman). If you knew about the function (as it seems that you did) or you could taken a look yourself (in the source code). Why didn't you help him, instead of giving us negative feedback for not providing 24/7 support?

Sure, that's your take on it. I'm not in here to provide 24/7 support and fixing every problem. I help out on topics I find interesting, and what I have time for. And if this is what you get for helping people out for three years... 

So with the lack of time, we have started putting "help wanted" on things we don't plan to solve ourselves in a timely manner. I where planning on solving #196 next month on my vacation and who knew; Maybe I got the feeling and emptied the queue ones more.

**Comment by duck7000** [comment]
Wow.. here we go again

I never said anything about quote, personal support,24/7 support etc enquote


`Now in the heat of "battle", it appears we already have that function (thanks @tboothman). If you knew about the function (as it seems that you did) or you could taken a look yourself (in the source code). Why didn't you help him, instead of giving us negative feedback for not providing 24/7 support?`
Well if i knew about this don't you think i would have told the poster this..

```
The problem here is the discoverability of the Person class. Clearly this functionality is available but if you're at the Title class there's no obvious link between the people it returns and the Person class.

@umair33

$title = new \Imdb\Title(133093);

$directors = $title->director();

foreach ($directors as $director) {
    $person = new \Imdb\Person($director['imdb']);
    echo "{$person->name()}: {$person->photo()}\n";
}
Lana Wachowski: https://m.media-amazon.com/images/M/MV5BMjEzMTc2MDQ5OV5BMl5BanBnXkFtZTcwNjkzNDY0OA@@._V1_UX214_CR0,0,214,317_AL_.jpg
Lilly Wachowski: https://m.media-amazon.com/images/M/MV5BMTU1Mjc1MjkzNV5BMl5BanBnXkFtZTgwOTc1NDQ1ODE@._V1_UX214_CR0,0,214,317_AL_.jpg
I'll mention the person class in the tldr at the top of the readme. The search classes are mentioned further down, one of which does return Person, but they're probably a bit lost in the massive config explanation section
```
Well this i didn't know, i only use the director method and image url is not available in that method.. That is what i told the poster. tboothman you used another method to get the image url from the person involved, i never use it in this way, that is why i added some funcionallity in some methods that i thought where missing

The only thing that really bothers me is the lack of communication if somebody post a issue, mostly nobody respond if that issue is not something the maintainers are going to fix or add. 
I don't and didn't asked for support cerainly not 24/7! I only ask for simply A reaction. If the maintainers are not interested in anything why you just say so. I don't ask for fixes, just a reaction, that's all. if nobody response then there is no communication or discussion possible

And this:
`Of course we are willing to merge good features, why wouldn't we accept an extension that's not a breaking change? Like you said. We merged your function to start with. So why would we just ignore you in the future...`
Sure you did merge this but it was a very hard struggle to even get the maintainers attention and to explain exactly what i added

The reason why i closed the 2 pull requests.. well lack of interest, at least it appeard that way because there was no reaction at all.
I hope you all see my point know

I still want to make this library better for all users, so if you can bear me i will consider adding pull requests again.

**Comment by jreklund** [comment]
Yeah, I'm sorry if that post (and this one) offends you. I don't take kindly (you may have noticed...) people criticize what I should do in my spare time. Specifically when it's a matter of 4 days, sure there are issues here (like this one) not getting any answers.

And other issues not receiving updates since december, but that dosen't mean we don't care. We have commented and fixed other issues after that. There are one "long timer" like yourself that opened one of the issues, I just hope that person know that we will take care of things. When we are able to. We have fixed everything else he/she have submitted.

> I think that the poster didn't know that picture url not is included in this method because there are other methods that do include it

This are that part that made med think you knew what where going on. "other methods..."

Personally If I don't answer something, I don't have anything to add to the subject at hand. If you look back at the closed issues we (the maintainers) have answer or solved everything. Or the Author have closed the issue themselves, either the issue are temporary or they have found a fix for it.

Nobody (the community) are welcome to contribute, that's not something we can control. We are happy for all the help we can get, if you want to answer and help us fix every issue, go for it! All issues that are opened will be taken care of, or we would have said something (and closed them). That may just be how I handle things. I'm interested in fixing bugs, that's why I commented on those.

What can I say, it's been a busy year. And you got the answer in that thread why you didn't get anyone's attention. It looked like duplicate code that we didn't have the time to look at it. I can get that you feel disappointing if you bumped something and still not getting a response, after three weeks. But closing something after 4 days... not even a weekend have gone by. Sure you opened a closed one of them. But I don't handle closed stuff.

You are more than welcome fixing your and/or other issues, submitting pull requests. But let us have a couple of more days next time. This are my priority to look at things:
1. Bugs
2. Feature requests
3. Tests
4. New features

Feature requests not only need to look good, they need to work. So we need to test them and write some tests for them. If none have been provided. Both of your feature requests didn't include any tests, so we have to write them. So I looked at them, and would come back later.

**Comment by duck7000** [comment]
@jreklund 
You made it perfectly clear how you stand in all this, and appreciate it that you explained it.

Those pull request closed after 4 days was more out of frustration from previous discussions so i got tired of it and closed it. maybe i should have left it open
If there be a next pull request i will leave it open for a while.
And basicly your saying that althought i made a pull request that might be of interest it won't be merged because it is incomplete, lacking tests? I didn't know that is part of the job and appologies for that.

And to all, this was not ment to rant or upset anyone, only of my frustration. maybe because i'm not a proffesional programmer so i may not understand the point of view from your side.

From a user point of view i find it confusing to have to use another class (person in this case) to get the image url from director? in my view it doesn't make any sence, i would have include that in the director method. I never use the person class
You see that developers and users sometimes differ from view, it may be that my frustration comes from this point

**Comment by jreklund** [comment]
@duck7000 Yeah, no worries and sorry that I behaved like a complete dick about it.

That's cool, we didn't know that! You aren't required to write tests, but if you have left them out, we need to make them ourselves. That's why we could not merge your pull requests on the spot. We probably didn't have the time that weekend (to write tests).

It's all good, now that we have cleared the air.

It's technically possible to load the Person class within Title to grab all extra goodies, but as this are a scraper it would mean extra overhead to download all personal data for all titles. It would be super slow if you don't what that data at all. 

Lets take Matrix for an example, we get the information from here:
https://www.imdb.com/title/tt0133093/fullcredits

And there are no images for directors on that page, that means we need to load Person and grab it from their bio page.
https://www.imdb.com/name/nm0905154/
https://www.imdb.com/name/nm0905152/

That's the reason we need to use classes, the information are not there. In this case it would "just" be two pages more to grab, but it stacks up.

**Comment by duck7000** [comment]
`t's technically possible to load the Person class within Title to grab all extra goodies, but as this are a scraper it would mean extra overhead to download all personal data for all titles. It would be super slow if you don't want that data at all.`
Exactly what i thought, too much overhead for useless information if you are just looking for example 1 image url.

Personally i would keep those 2 classes separated and code the same information in all methods (if available), but i understand that will be a lot of work and cetainly understand that you don't want to spent the time.
And if the images are not available then the user got 2 choices, either satisfy with no image or grab it through the person page (if available), Agree that would be okay, but like i said i didn't know that and never use the person class, certainly not for just a image url.
So thanks tboothman to highlight that in the readme.

And thanks for clearing the air!

**Comment by tboothman** [comment]
Well we never heard back from the questioner so I'll assume this is resolved.

Personally I would (if this were code just for me and not already being used by other people) change any method that has results relating to another class to return instances of that class. Makes it a bit simpler to see what's possible .. at the disadvantage of it being less explcit what data is available for free.
Take https://github.com/tboothman/imdbphp/blob/master/src/Imdb/TitleSearch.php#L25 for example. The search results are instances of the Title class
