### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by bombolini** [tboothman/imdbphp#210]
Hello,
Can't find detailed info explaining installation procedures.
ubuntu 16.04 with php 7.2.15

Thank you

#### Type

Bug | Question | Feature request

#### Code
```php
// Avoid posting hundreds of lines of source code.
// Edit to just the relevant portions.
```

**Comment by tboothman** [comment]
Did you read the readme? https://github.com/tboothman/imdbphp#installation

**Comment by bombolini** [comment]
Hello,
Thank you for your reply. To be honest, I need to confess that I have just a bit confused by your answer.
If you think that the existence of a readme file is enough to say "well explained help manual", anyway...
Do you think that below explanation is good enough:

```
Install the files:
Composer (recommended). Include the imdbphp/imdbphp package. -->No need to download composer.. Ok, include *.php , it's okay.. 
Git clone. Checkout the latest release tag. ---> ok, we already did . Are you sure that just git clone is enough for installation? Didnt work at my end.
APT/RPM/ARK packages. Updated soon after a release. --> no need apt/rpm packages
Zip/Tar download -> what is this?
```

**Comment by duck7000** [comment]
Well it is not that hard, do you know anything about php?

In the code tab, click the green button and download the complete source, or use one of the releases.
Extract it somewhere in your program directory and include bootstrap.php so that it gets loaded when your program is loaded.

Then load the search class, like stated on the first page, in your program to get results:

```
$title = new \Imdb\Title(335266);
$rating = $title->rating();
$plotOutline = $title->plotoutline();

# Find out about the director
$person = new \Imdb\Person($title->director()[0]['imdb']);
$name = $person->name();
$photo = $person->photo();
```
I never use composer so can't say anything about that. So yes there are different methods to install this library (through apt, composer or manual like i do)

**Comment by tboothman** [comment]
There aren't step by step instructions because (unless you're using composer, and i could have written `composer require imdbphp/imdbphp` there) the instructions are different depending on what you're trying to do exactly and what you're wanting to use to do it.

How do you want to download the files? I don't know. I suggested a git clone but as duck7000 says you could download a zip file of the master branch or download a release zip as the readme suggests or use the github cli or use github desktop.

What do you want to do with them? I can't possibly know .. so I said in the readme you need to include the bootstrap file. I'm not going to literally write out how to do that because I don't know where it will be relative to the code you're writing.

This library is just a bunch of php files, it doesn't do anything so there's not an obvious do a then b then c then d then tada you can see the output.


If there's obvious stuff missing I'll correct the readme (I have already tweaked it a little) but I'm unaware of how to explain what you're asking for (I genuinely don't know how to answer your question without way more information on your context)

https://www.w3schools.com/php/php_includes.asp ?

**Comment by bombolini** [comment]
Thank you for your reply @tboothman,
When I replace imdb.class.php by bootstrap.php in my php file, it gives fatal error.
When I keep imdb.class.php in file, I mean left as it is, `$description = ($IMDB->getDescription()); `returns requested information.
Are you sure that just `git clone` is enough for correct installation?

**Comment by duck7000** [comment]
> When I replace imdb.class.php by bootstrap.php in my php file, it gives fatal error.

Who said anything about replacing this class?
Leave it like it is and include bootstrap.php like tboothman said with the w3schools link.

I get the feeling you don't have a clue about php at all?

Like tboothman asked, where or how you want to use this library?
