### ISSUE TITLE
Support for Namespace and PSR

### ISSUE THREAD

**Issue by joglomedia** [tboothman/imdbphp#23]
This awesome library will be more awesome if support for Namespace and PSR-standard

**Comment by tboothman** [comment]
Some of the people who use this library live in the past. I had to remove some short array syntax I'd used because it didn't work for some (which in fairness is 5.4 and 3 years younger than 5.3).
Obviously I agree it'd be better, but why in your opinion would it make it so much better?
Realistically the only change to the end user would be you'd do `new \imdb\title()` instead of `new imdb()`

**Comment by joglomedia** [comment]
as I start learning PHP in the new era of PHP community and I start creating new project using framework which several of them now going to standardized under PSR, just thinking if this code rewritten in psr standard it will looks pretty :D

**Comment by IzzySoft** [comment]
IMHO "looking pretty" doesn't justify breaking it for those already relying on the current "status quo" (remember, all places where one `include()`s or `require()`s classes would need to be changed). Some users may have auto-updates turned on (e.g. via the repo), and would have a bad surprise when e.g. returning from holidays seeing their site being broken for weeks.

Namespaces are good for preventing "overlaps". I don't think there's that big danger any other library uses similar names for its files/classes, so I don't see any urgency here. It's a nice idea, though – but it should be introduced in a way posing less "danger of breaking things". I could e.g. imagine doing so with the initial v3 release, renaming the package from `imdbphp2` to `imdbphp3` at the same time – thus auto-updates wouldn't fetch it, and a "big warning" for the "migration path" would be perfectly sufficient.
