### ISSUE TITLE
debug text [Cache] Purging old cache entries should appear later

### ISSUE THREAD

**Issue by jcvignoli** [tboothman/imdbphp#245]
Hi,

I'm using imdbphp library for a wordpress plugin, [Lumière](https://wordpress.org/plugins/lumiere-movies/) and the [GIT](https://github.com/jcvignoli/lumiere-movies) 

Thanks so much tboothman for continuing Ozzy project. You improved it a lot, congrat!

First, please not I'm not an experienced developper, I might face newbie issues from time to time.

I'm trying to implement a proper debug in my plugin. However, when activating imdbphp debugging, a debug message is returned before the html declaration:
[Cache] Purging old cache entries

This message, which is incorrect html (not an important issue since it's a debugging message), breaks the layout as it is thrown before the text.

I tried to edit logger.php and cache.php looking for a solution, but I failed.

Is there anything that could be done?

Thanks!

**Comment by tboothman** [comment]
This might be slightly helpful https://github.com/tboothman/imdbphp#replacing-the-default-logger-which-echos-coloured-html-and-is-disabled-by-default
The logger built into imdbphp is pretty useless, which is why it's disabled.
You can replace it with any psr-3 logger as the readme says. There's a bunch of them on packagist https://packagist.org/providers/psr/log-implementation
You could just copy/paste the imdbphp logger to create your own logger and change what's in the log method.

**Comment by jcvignoli** [comment]
I thank you very much. I've been able to fix my issue!

Thanks also for maintaining this great library, much appreciated.
