### ISSUE TITLE
Throw exceptions when bad things happen .. don't just return empty strings

### ISSUE THREAD

**Issue by tboothman** [tboothman/imdbphp#26]

**Comment by IzzySoft** [comment]
Might break existing apps relying on the "empty return", so I'd make that optional maybe (config option?)

**Comment by tboothman** [comment]
The problem I personally have with the current approach is it's hard to tell the difference between a film with little/no information and a http error. By throwing an exception you know for sure that something's gone wrong. A film with no year would still be a 0 or null but if requesting the page fails an exception would be throw.
This is a fairly major interface change .. but it feels to me like supporting the exceptions would make user's applications better, even if it is a little work to do so.
I'm certainly willing to be convinced that it's worth putting a config option in but I know in both the applications I use this library all the imdb code is in one file and sticking a big old try catch around it is hardly much effort.

**Comment by IzzySoft** [comment]
Might be different with different apps – and again depending on how many places throw exceptions. For a "full-draw" you'd call a lot of methods, which means there could be a lot of exceptions thrown, and thus a lot of places to fix. Which is why I would make them optional – at least for a while, to give devs the chance to "slowly adjust". Only a thought you *might* consider – decision is yours, master of the code  :innocent:
