### ISSUE TITLE
PR processing time

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#281]
A very simple question:
Why does it here in general take so much time before a PR request is even looked at?

I have several PR's here and some does not even get a response while it is sometimes asked for in the issue tracker?
Others are looked at en suggestions are made and followed by me but there is no more response to finish the PR?

I think this is a legit question and by no means meant as rant or to fire up things here. I'm just concerned that if it takes forever to merge a PR no one will benefit from it

What's your thinking of this?

**Comment by jreklund** [comment]
I will answer in here instead of in all individually PR I have been tagged in or assigned as of late. 

> Why does it here in general take so much time before a PR request is even looked at?
> Others are looked at en suggestions are made and followed by me but there is no more response to finish the PR?

Lack of time and personal interest. I'm already working 8 hours at work coding, writing documentation, code review, test and deploy. Got some part time gigs doing the same thing, so I want to do something else on my spare time. Tried to do some PR last year when there where only one, another popped up and BAM there like 10 of them. So I signed out of Github and left some of them unfinished, it's not worth my time.

My personal project broke that are depending on this software, so I signed in - wrote some code and released a new version. And now I will probably leave again until some of the features I require break again.

**Comment by duck7000** [comment]
First of all thanks for your response! I'll appreciate it.

Well in your case, after reading your comment above i fully understand that this project is on your back burner.
I'm glad you told me this because it is clear that you are likely not be working on this project, and i fully understand that.

I found it however very frustrated that there were no more responses in the PR's your tagged in (and now i understand why) Maybe it was better to start a issue and explain that you no longer actively involved in this project then to be silent? I would have appreciate that

Thanks for your support and conversations in my PR's, i learned al lot from it.
I wish you best of luck in the future

**Comment by duck7000** [comment]
The none response from the other maintainer of imdphp is a pity as i gladly known his arguments about it.
