### ISSUE TITLE
Error when following 301 redirects

### ISSUE THREAD

**Issue by jonatanalvarsson** [tboothman/imdbphp#3]
The function call in getWebPage() in [mdb_base.class.php#130](https://github.com/tboothman/imdbphp/blob/master/mdb_base.class.php#L130) is using $target retrieved from the HTTP header field **location**. But the location does not contain the full URL, only "/title/tt#######/". Below is the header for http://www.imdb.com/title/tt2768262/

```
301 Moved Permanently
content-length:0
vary:User-Agent
server:Server
location:/title/tt2386868/
date:Thu, 09 Oct 2014 20:06:09 GMT
x-frame-options:SAMEORIGIN
p3p:policyref="http://i.imdb.com/images/p3p.xml",CP="CAO DSP LAW CUR ADM IVAo IVDo CONo OTPo OUR DELi PUBi OTRi BUS PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA HEA PRE LOC GOV OTC "
```

**Comment by tboothman** [comment]
#147

**Comment by tboothman** [comment]
Only took 4 years but there's a function now `\Imdb\Title::real_id()` that returns the id that's parsed from the body of the title page - which will show up a redirect.
I left this alone at the time because I wanted a more elegant solution that just worked rather than having users put in any extra effort .. but I couldn't think of anything.
An exception on an ID redirect sounded like an idea but it would've just meant anyone using an id that is redirected would have to change the ids in their DB or something after the code change.
I was tempted to change `Title::imdbid()` but that's used internally and could have some consequences if it's expected to be the same as the id that went into the constructor

**Comment by jonatanalvarsson** [comment]
Great! Thank you!

https://www.imdb.com/title/tt4340196/
https://www.imdb.com/title/tt5020352/
:)
