### ISSUE TITLE
v3.0.0 inconsistencies

### ISSUE THREAD

**Issue by IzzySoft** [tboothman/imdbphp#33]
The `Makefile` hasn't been updated to reflect the huge structural changes implemented with v3.0.0, hence:

* `.deb`/`.rpm` builds are impossible for the release tag, hence
* the Prod demo (reflecting the latest release) will not be up-to-date

Additional issues due to the restructuring:

* the Dev demo (reflecting the current `master` branch) <strike>will be</strike> is broken
* applications using IMDBPHP won't be able to easily use the new version (no compatibility layer; for examples how those could look like, see e.g. [MarkdownExtra](https://michelf.ca/projects/php-markdown/extra/): we could have corresponding files in the "old locations" taking care for that, such as `imdb.class.php` having a pseudo `imdb` class extending the real one), which especially affects those currently unmaintained (as e.g. phpVideoPro), where such a "compatibility layer" had easily fixed it.

Sorry, @tboothman – but that's why I said we should communicate when you're done with restructuring, but *before* you merge that into `master` :mask:

**Comment by tboothman** [comment]
I have no idea what the makefile does so I can't change that myself. Should just be a case of changing the folder / file names in it.

I know everything's changed, and that's why there's a major version change and I've done a fairly long release description to help people migrate. I'll be migrating my projects later today and it should be as easy as it was to migrate the tests. If not i'll add in some more notes and maybe there'll be a 3.0.1.

If people want to keep the old classnames (they really shouldn't) then making a file that extends the old classnames from the new ones would take someone a minute to make as I created a table with the mappings. There's absolutely no way though that I'm going to put some shells of files back in the root for backwards compatibility though. I might be wrong but I hope this will make people spend a few hours looking into composer / psr / autoloaders and get some good new practices from it.

**Comment by tboothman** [comment]
I'd certainly welcome any feedback though .. It's a little bizarre working on a library that I don't know a single user of .. yet trying to appease processes or viewpoints that may or may not exist.

**Comment by IzzySoft** [comment]
@tboothman you did a great job on that, definitely. We just need to work a little on our communication. I must have missed your notice for "structure-changes done, please do your part" – apologies for that. But I neither reported back "all OK, go on" :wink:

OK so far: I've hopefully fixed the [`Makefile`](http://en.wikipedia.org/wiki/Makefile) now (waiting for feedback from those very same people you're looking for – as I currently lack the time testing it myself). The dev demo also seems to be working again, so two points checked.

I'm hesistant making the current status package releases, as nothing of the new package structure has been verified so far. So there currently will be no DEB/RPM of the latest release. Which means, the Prod demo will stay out-of-sync as well; guess we can live with that for a few weeks (especially with the dev demo up and running again).

As for the "compatibility layer for older applications": Same thing as with the DEB/RPM. While it shouldn't be too hard to do (at least I hope so), I currently lack the time, so this will have to wait.

**Comment by IzzySoft** [comment]
You might have noticed I've stopped building packages. Unfortunately, too many issues with that since the reorg came with v3.0.0, sorry.

**Comment by tboothman** [comment]
I hadn't but maybe someone else had... but they certainly haven't said anything though. It's hard to tell though because there haven't been any breaks to the core functionality of imdbphp since 3.0 so anyone using the RPMs might not have bothered upgrading.

Fundamentally though the RPM for version 3 wouldn't be backwards compatible so maybe it's a reasonable time to drop support for it anyway. Using a git clone or composer is as good as RPMs and can just be a small additional task when moving from v2 to v3

**Comment by IzzySoft** [comment]
Afraid that's the only way to go now (and besides, there wasn't any RPM/DEB for v3 at all – latest packages are for v2.6.1).
