### ISSUE TITLE
Error for wrong iMDB id

### ISSUE THREAD

**Issue by mpol12** [tboothman/imdbphp#45]
I have several mistyped iMDB ids in my DB. When these ids are used with imdbPHP I get the an error saying
**Imdb\Exception\Http: Uncaught exception 'Imdb\Exception\Http' with message 'Failed to retrieve url [http://akas.imdb.com/title/tt1223602/]. Status code [404]' in /*'path_to_imdbPHP'*/src/Imdb/Pages.php**

This error breaks my script. It would be very useful if there was a small check function in imdbPHP which could be used to verify that the iMDB id we are using corresponds to an valid page. Is this something you would consider incorporating?

**Comment by nmpgaspar** [comment]
I guess you can catch the exception and do whatever logic you deem appropriate.

**Comment by tboothman** [comment]
I think this is the best I can do for you at the moment. I initially wasn't going to do this because as @nmpgaspar says you can easily do it yourself, but from user generated inputs it's not a bad idea to add that functionality.
Sadly though the exceptions are configurable off so I can't actually add it in as it won't work for everyone.

```php
function isValidID(\Imdb\Title $imdb) {
  try {
    $imdb->title();
    return true;
  } catch (\Imdb\Exception\Http $e) {
    if ($e->HTTPStatusCode == 404) {
      return false;
    }
    throw $e;
  }
}
```
