### ISSUE TITLE
person filmography not download

### ISSUE THREAD

**Issue by Alexisback** [tboothman/imdbphp#51]
and possible in "person" script download entire filmography?
Now there are only "Herself" and not movie

thank you

**Comment by tboothman** [comment]
I don't know what you mean.
`\Imdb\Person` has movies_actor() etc

**Comment by Alexisback** [comment]
sorry for my bad english

the "person" script does not download the entire filmography, only "Herself" (Selfs Filmography:) and (Biographical movies :)
They are not downloaded the list of films who recited


look at the attachment

[Linda Blair [IMDBPHP v3.2.0 Demo].zip](https://github.com/tboothman/imdbphp/files/189621/Linda.Blair.IMDBPHP.v3.2.0.Demo.zip)

**Comment by tboothman** [comment]
That's just the demo page to show some of the data you can get with the library and how you might use it, it's not particularly important if it works or not. Turns out that it doesn't look for filmographies for an actress, just an actor. You'll see if you try a male actor it will show their filmography.
I've merged the two together in 81384bca4d9a5fa34f8874cd0d37f234f1613d5b but I noticed there's #49 which I forgot about, so it might not end up looking exactly like this
