### ISSUE TITLE
Rewrite using xpath

### ISSUE THREAD

**Issue by decorate** [tboothman/imdbphp#54]
Any thoughts on updating the script to use xpath which is a much more robust way of parsing HTML. I have some of the functionality already written before discovering this library using xpath and it is much easier to maintain. Any interest in this?

**Comment by tboothman** [comment]
There's a little bit of xpath in it, but most is just regular expressions because that's how it's always been. Some things could and should be swapped to xpath because they'd be simpler, but some things are harder in xpath too. I certainly don't want to spend weeks rewriting hundreds of methods to use xpath because quite a lot of the methods aren't tested and there'd be very little benefit. I'll see if there are any obvious ones to swap the next time there's a site change.
