### ISSUE TITLE
Music credits for TV series

### ISSUE THREAD

**Issue by Tonza** [tboothman/imdbphp#66]
Hello

I'm trying to list music credits for TV series (for example House), but imdbphp returns empty results with composer(). Is there another command for that or is this bug?

**Comment by tboothman** [comment]
I'm not really sure what the composer method is meant to do, but the music credits i.e. http://gb.imdb.com/title/tt0412142/soundtrack?ref_=tt_trv_snd are fetched with `Title::soundtrack()`

**Comment by tboothman** [comment]
On The Matrix composer() Would get you Don Davis, because he's in the "Music By" section on http://www.imdb.com/title/tt0133093/fullcredits?ref_=tt_cl_sm#cast
There's a "Series Music by" section on http://www.imdb.com/title/tt0412142/fullcredits?ref_=tt_cl_sm#cast so I suppose if it looked for that as well then you'd get Jason Derlatka, Jon Ehrlich, Christopher Hoag, Jeremy Sweet for house. Is that what you'd like it to do?

**Comment by Tonza** [comment]
Yeah, "Series Music by" is not returned with composer() and that is what I would like to get.

**Comment by tboothman** [comment]
Started to implement this and I wonder if "Series Music Department" should be in there too, or that should be the main one?
The Wire http://www.imdb.com/title/tt0306414/fullcredits?ref_=tt_cl_sm#cast has no "Music By" section, but does have a "Series Music Department" which includes whoever did the title.
In House, also, the theme track is only mentioned in the "Series Music Department" section

**Comment by Tonza** [comment]
It seems that in some TV series there is "Series Music Department" (imdb.com/title/*/fullcredits/music_department) and some have "Series Music By" (imdb.com/title/*/fullcredits/composer) and some have both. Neither is returned with composer().
