### ISSUE TITLE
Ratings

### ISSUE THREAD

**Issue by DeNeDe** [tboothman/imdbphp#71]
Any way to calculate ratings as stars ? If a movie has 6.5 rating to be 6 and a half stars from 10 stars.
Just like on imdb site. Or the code is already here? Because i can't see how to call it.
And also can't find how to call the movie rated code as PG-13 or Mature.. and so on
Ohh yeah..release date can't find how to call it either..just the year

**Comment by tboothman** [comment]
Sorry, I didn't get much past the first sentence of this when I first read it because you're asking how to program, not how to use this library.
You can get the age ratings from `Title::mpaa()`, and in theory you can get the release date from `Title::releaseInfo()` as it has the releases dates for every country.
I think at the time neither of those bits of information were available in a localised form as they are currently on the title page. If you/someone wants to add that functionality, please do.

**Comment by DeNeDe** [comment]
Hmm, why was it hard? Instead of  4.5/10 to be displayed 10 stars but only  4 and half star to be full, the rest empty. :)

**Comment by tboothman** [comment]
lol, you nearly goaded me into writing that for you.
There are star images in the demo/imgs/showtimes for some reason ...
Multiply the rating by 10, then use http://stackoverflow.com/questions/4133859/round-up-to-nearest-multiple-of-five-in-php to round it to 5 and use that numbered gif
