### ISSUE TITLE
Missing required file /src/MoviePosterDb/Movie.php

### ISSUE THREAD

**Issue by jonatanalvarsson** [tboothman/imdbphp#74]
[bootstrap.php#L19](https://github.com/tboothman/imdbphp/blob/v5.0.1/bootstrap.php#L19) requires '/src/MoviePosterDb/Movie.php' but this file seems to be removed in 5.0.1.

**Comment by tboothman** [comment]
Sorry about that, that's a pretty dumb oversight.
I've modified my tests to use that bootstrap file so that shouldn't happen again ... although I'm almost certainly going to forget to add new files to it and annoyingly phpunit uses composer's autoloader so I won't notice.
Anyway v5.0.2 is released and that'll sort the problem

**Comment by jonatanalvarsson** [comment]
Thanks! Hey, don't be too hard on yourself. Keep up the good work!
