### ISSUE TITLE
Extend the method Recommendations

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#81]
Hi all

Is it a option to extend the method recommendations with the following:
Poster
Plotoutline
rating
genre

Maybe something like the actors method?

It's just a thought and i don't know if there is any intrest to this at all.

Ed
![recommendations](https://cloud.githubusercontent.com/assets/15360048/22404546/29867c2c-e633-11e6-8d28-86fdf5160980.jpg)

**Comment by duck7000** [comment]
Thanks for the tidy up of the recommendations method!

If nobody has any interest in extend this method you may close this one too.
It was just a thought though

I'll appreciate all your work, but i got to ask about the soundtrack method, any further thoughts?

**Comment by tboothman** [comment]
If you want to do it, go for it.

I don't mind fixing bugs for code I don't use, or occasionally adding a feature I'll never use but honestly parsing html and endless self debates about backwards compatibility with peoples theoretical usage of this library isn't especially fun.

There's tons of examples of how to do everything, and unit tests so you can't mess anything up. You'd be joining a big family of 1 person (yyanavichus) other than me/izzy who's contributed something new to the repo since it's been on github.

**Comment by duck7000** [comment]
Oke i understand

I'm glad i'm joining the family haha

I think about it to extend it but i'm also self debating the use of it thought.

Let's forget about it for now, but i'll appreciate your input!
