### ISSUE TITLE
Poster images fetched are non-optimal

### ISSUE THREAD

**Issue by spiritualized** [tboothman/imdbphp#91]
The images selected are often not those shown on a given IMDb page.

For example, with "Song of the South" http://www.imdb.com/title/tt0038969/

I am given the following image:

https://images-na.ssl-images-amazon.com/images/M/MV5BOTQ4NzM1MjIyM15BMl5BanBnXkFtZTYwNjA2MTc4._V1_.jpg

I am sure to send language = 'en-US', however my host is located in a non-English country. Could this be the problem?

**Comment by jreklund** [comment]
Hi, try to use `language = en` instead. They don't accept en-US anymore.

**Comment by spiritualized** [comment]
That fixed it - thanks.

**Comment by tboothman** [comment]
That's odd.
http://www.imdb.com/title/tt033797
If I use "en-GB" I get "Die Hard 4.0" although bizarrely with a poster that says live free or die hard.
If I use "en-US" or "en" I get the title of "Live Free or Die Hard" and the same poster.
What is the difference between en and en-US? Surely en-US is sent by users in America.

If en-US is really broken I'll change it in the docs for the config

**Comment by jreklund** [comment]
en = Fallback - Whatever is avaible (America, on IMDb)
en-US = America
en-GB = UK / United Kingdom
On this particular movie (Die Hard) you won't see any great differences. Just the localized name, release date etc. Specific for that country.

All browsers report their preferred languages.
Mine reports itself as this `sv,en-US;q=0.8,en;q=0.6` or `sv-SE,en-US;q=0.8,en;q=0.6`.
sv = Swedish
sv-SE = Swedish (Sweden)
And fallback into en-US first, and if everything else fail, use English.

In some occasions when you specify en-US it will just take that choice and not fall back to any other English alternatives and go for IP-adress. So `language = 'en-US,en'` are better. If you want the American title, and if that fails anything in English.

IMDb looks in this order:
1. Browser (Accept-Language)
2. IP

But sometimes it's getting unsure and goes for number 2 instead... It can't be curl's fault, due to the fact you actually specify a custom language header.
